import random
r=random.randrange(1,11)
print("When done with instruction press ENTER")
print("Choose a number between 1 to 10")
input()
print("Double your number")
input()
print("Add "+str(r))
input()
print("Divide it into half")
input()
print("Subtract your number")
input()
print("Are you left with "+str(r/2)+"???")
